### ISSUE TITLE
PHP 7.2 Compatibility

### ISSUE THREAD

**Issue by travislopes** [gravityflow/gravityflowformconnector#8]
PHP 7.2 deprecates `create_function()` which is used by the `prepopulate_input()` method. Maybe a version compare conditional that uses an anonymous function for PHP 7.2.0 and up?

https://github.com/gravityflow/gravityflowformconnector/blob/master/class-form-connector.php#L268

**Comment by stevehenty** [comment]
Thanks, @travislopes. Fixed in #12.
